export const apiDashboardStyles = `
:root{color-scheme:dark;--bg:#07150d;--panel:#10261a;--line:#274534;--green:#55c878;--gold:#f4b942;--muted:#9eb1a4}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 80% 0,#173e27 0,transparent 36%),var(--bg);color:#f7fbf8;font:15px/1.5 Inter,Segoe UI,Arial,sans-serif}.shell{max-width:1180px;margin:auto;padding:42px 24px 64px}.top{display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid var(--line);padding-bottom:22px}.brand{display:flex;align-items:center;gap:12px;font-weight:800;letter-spacing:.02em}.mark{display:grid;place-items:center;width:42px;height:42px;background:var(--gold);color:#10261a;border-radius:12px}.status{display:flex;align-items:center;gap:9px;color:#cbe8d3}.dot{width:9px;height:9px;background:var(--green);border-radius:50%;box-shadow:0 0 0 6px #55c8781c}.hero{padding:76px 0 48px;max-width:760px}.eyebrow{color:var(--green);font-weight:800;text-transform:uppercase;letter-spacing:.16em;font-size:11px}h1{font-size:clamp(42px,7vw,76px);line-height:.98;letter-spacing:-.055em;margin:16px 0 22px}.hero p{font-size:18px;color:var(--muted);max-width:670px}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin:16px 0 42px}.card,.endpoint{background:linear-gradient(145deg,#132c1e,#0d2116);border:1px solid var(--line);border-radius:18px;padding:24px}.card small{color:var(--muted);text-transform:uppercase;letter-spacing:.12em}.card strong{display:block;font-size:28px;margin-top:12px}.card strong.ok{color:var(--green)}h2{font-size:24px;margin:0 0 18px}.endpoints{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.endpoint{display:flex;align-items:center;gap:14px}.method{background:#55c8781a;color:var(--green);border:1px solid #55c87855;border-radius:8px;padding:5px 9px;font:700 11px/1 ui-monospace,SFMono-Regular,Consolas,monospace}.endpoint code{color:#fff;font-size:14px}.endpoint p{color:var(--muted);margin:4px 0 0;font-size:12px}.footer{display:flex;justify-content:space-between;gap:18px;margin-top:42px;padding-top:22px;border-top:1px solid var(--line);color:var(--muted);font-size:12px}.footer a{color:var(--green)}@media(max-width:720px){.shell{padding:24px 16px 44px}.hero{padding:54px 0 34px}.cards,.endpoints{grid-template-columns:1fr}.top{align-items:flex-start}.status{font-size:12px}.footer{flex-direction:column}}
`;

export function apiDashboardHtml() {
  const endpoints = [
    ["GET", "/api/health", "État du service"],
    ["GET", "/api/products", "Catalogue et filtres"],
    ["GET", "/api/parts", "Pièces et accessoires"],
    ["POST", "/api/quotes", "Demandes de devis"],
    ["POST", "/api/auth/register", "Création de compte"],
    ["POST", "/api/auth/login", "Connexion sécurisée"],
  ];
  return `<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AgriFrance API — Console</title><meta name="description" content="Console opérationnelle de l’API AgriFrance"><link rel="stylesheet" href="/dashboard.css"></head><body><main class="shell"><header class="top"><div class="brand"><span class="mark">AF</span><span>AgriFrance<br>API Platform</span></div><div class="status"><span class="dot"></span>Service opérationnel</div></header><section class="hero"><span class="eyebrow">Infrastructure commerciale</span><h1>Une API robuste pour piloter AgriFrance.</h1><p>Catalogue, authentification, devis et gestion des pièces réunis dans un service sécurisé, versionné et prêt pour les applications clientes.</p></section><section class="cards" aria-label="Indicateurs"><article class="card"><small>État général</small><strong class="ok">Opérationnel</strong></article><article class="card"><small>Protection</small><strong>Helmet + CORS</strong></article><article class="card"><small>Format</small><strong>REST / JSON</strong></article></section><section><h2>Points d’accès principaux</h2><div class="endpoints">${endpoints.map(([method,path,label]) => `<article class="endpoint"><span class="method">${method}</span><div><code>${path}</code><p>${label}</p></div></article>`).join("")}</div></section><footer class="footer"><span>AgriFrance API · Environnement sécurisé</span><a href="/api/health">Consulter la santé du service →</a></footer></main></body></html>`;
}
