"use client";

import { useState, type FormEvent } from "react";
import Link from "next/link";
import { AppShell } from "@/src/components/AppShell";

type User = { email:string; role:string };
const api=(process.env.NEXT_PUBLIC_API_URL??"https://agrifrance-api.onrender.com").replace(/\/$/,"");

export function AccountPage(){
  const [mode,setMode]=useState<"login"|"register">("login"); const [form,setForm]=useState({name:"",email:"",password:""}); const [message,setMessage]=useState(""); const [user,setUser]=useState<User|null>(null); const [csrf,setCsrf]=useState(""); const [busy,setBusy]=useState(false);
  const submit=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setMessage("");try{const response=await fetch(`${api}/api/auth/${mode}`,{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify(form)});const payload=await response.json();if(!response.ok)throw new Error(payload.error??"Action impossible");if(mode==="register"){setMode("login");setMessage("Compte créé. Connectez-vous pour continuer.");}else{setUser(payload.user);setCsrf(payload.csrfToken);setMessage("Connexion sécurisée réussie.");}}catch(error){setMessage(error instanceof Error?error.message:"Service indisponible");}finally{setBusy(false)}};
  const refresh=async()=>{setBusy(true);try{const response=await fetch(`${api}/api/auth/refresh`,{method:"POST",credentials:"include",headers:{"x-csrf-token":csrf}});const payload=await response.json();if(!response.ok)throw new Error(payload.error??"Session expirée");setUser(payload.user);setCsrf(payload.csrfToken);setMessage("Session renouvelée.");}catch(error){setMessage(error instanceof Error?error.message:"Session expirée");}finally{setBusy(false)}};
  const logout=async()=>{setBusy(true);try{const response=await fetch(`${api}/api/auth/logout`,{method:"POST",credentials:"include",headers:{"x-csrf-token":csrf}});if(!response.ok)throw new Error("Déconnexion impossible");setUser(null);setCsrf("");setMessage("Vous êtes déconnecté.");}catch(error){setMessage(error instanceof Error?error.message:"Déconnexion impossible");}finally{setBusy(false)}};
  return <AppShell>{user?<main className="account-access"><span className="eyebrow dark">ESPACE SÉCURISÉ</span><h1>Bonjour.</h1><p>{user.email} · rôle {user.role}</p><div><Link className="btn orange" href="/catalog">Voir le catalogue</Link><button className="btn outline" onClick={refresh} disabled={busy}>Rafraîchir la session</button><button className="btn outline" onClick={logout} disabled={busy}>Se déconnecter</button></div>{message?<p role="status">{message}</p>:null}</main>:<main className="account-access"><span className="eyebrow dark">ESPACE PROFESSIONNEL</span><h1>{mode==="login"?"Connexion":"Créer un compte"}</h1><p>Accès protégé par cookies HTTP-only, rotation de session et limitation des tentatives.</p><form onSubmit={submit}>{mode==="register"?<label>Nom complet<input required minLength={2} value={form.name} onChange={event=>setForm({...form,name:event.target.value})}/></label>:null}<label>E-mail<input required type="email" autoComplete="email" value={form.email} onChange={event=>setForm({...form,email:event.target.value})}/></label><label>Mot de passe<input required type="password" minLength={12} autoComplete={mode==="login"?"current-password":"new-password"} value={form.password} onChange={event=>setForm({...form,password:event.target.value})}/><small>12 caractères minimum avec majuscule, minuscule, chiffre et symbole.</small></label><button className="btn orange" disabled={busy}>{busy?"Veuillez patienter…":mode==="login"?"Se connecter":"Créer mon compte"}</button></form><button className="account-switch" onClick={()=>{setMode(mode==="login"?"register":"login");setMessage("")}}>{mode==="login"?"Créer un compte":"J’ai déjà un compte"}</button>{message?<p role="status">{message}</p>:null}</main>}</AppShell>;
}
