"use client";

import { useState, type FormEvent } from "react";
import Link from "next/link";
import { AppShell } from "@/src/components/AppShell";

type User={email:string;role:string};type Quote={reference:string;product_slug:string;status:string;total_cents:string|null;currency:string;created_at:string};type Order={id:string;status:string;currency:string;total_cents:string|null;created_at:string;items:Array<{name:string;quantity:number;unit_price_cents:string|null}>;payments:Array<{status:string;amount_cents:string;provider:string;created_at:string}>;delivery:null|{status:string;carrier:string|null;tracking_number:string|null;estimated_at:string|null;delivered_at:string|null}};type Overview={orders:Order[];quotes:Quote[]};
const api=(process.env.NEXT_PUBLIC_API_URL??"https://agrifrance-api.onrender.com").replace(/\/$/,"");const money=(cents:string|null,currency="EUR")=>cents===null?"Sur devis":new Intl.NumberFormat("fr-FR",{style:"currency",currency}).format(Number(cents)/100);const orderSteps=["pending","confirmed","processing","shipped","delivered"];

export function AccountPage(){
  const [mode,setMode]=useState<"login"|"register">("login");const [form,setForm]=useState({name:"",email:"",password:"",otp:""});const [message,setMessage]=useState("");const [user,setUser]=useState<User|null>(null);const [csrf,setCsrf]=useState("");const [overview,setOverview]=useState<Overview|null>(null);const [busy,setBusy]=useState(false);
  const loadOverview=async()=>{const response=await fetch(`${api}/api/customer/overview`,{credentials:"include"});const payload=await response.json();if(!response.ok)throw new Error(payload.error??"Suivi indisponible");setOverview(payload);};
  const submit=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setMessage("");try{const response=await fetch(`${api}/api/auth/${mode}`,{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify(form)});const payload=await response.json();if(!response.ok)throw new Error(payload.error??"Action impossible");if(mode==="register"){setMode("login");setMessage("Compte créé. Connectez-vous pour retrouver vos devis et commandes.");}else{setUser(payload.user);setCsrf(payload.csrfToken);await loadOverview();}}catch(error){setMessage(error instanceof Error?error.message:"Service indisponible");}finally{setBusy(false);}};
  const logout=async()=>{setBusy(true);try{await fetch(`${api}/api/auth/logout`,{method:"POST",credentials:"include",headers:{"x-csrf-token":csrf}});}finally{setUser(null);setOverview(null);setCsrf("");setBusy(false);}};
  if(!user)return <AppShell><main className="customer-auth"><section><span>ESPACE CLIENT AGRIFRANCE</span><h1>Suivez votre projet, de la demande à la livraison.</h1><p>Retrouvez vos devis PDF, commandes, paiements et informations de livraison dans un espace unique et sécurisé.</p><div><b>✓ Devis téléchargeables</b><b>✓ Suivi de commande</b><b>✓ Historique des paiements</b></div></section><form onSubmit={submit}><small>{mode==="login"?"BON RETOUR":"CRÉER VOTRE ESPACE"}</small><h2>{mode==="login"?"Connexion":"Inscription"}</h2>{mode==="register"?<label>Nom complet<input required minLength={2} value={form.name} onChange={event=>setForm({...form,name:event.target.value})}/></label>:null}<label>E-mail<input required type="email" autoComplete="email" value={form.email} onChange={event=>setForm({...form,email:event.target.value})}/></label><label>Mot de passe<input required type="password" minLength={12} autoComplete={mode==="login"?"current-password":"new-password"} value={form.password} onChange={event=>setForm({...form,password:event.target.value})}/><small>12 caractères, avec majuscule, minuscule, chiffre et symbole.</small></label>{mode==="login"?<label>Code de sécurité <small>(si activé)</small><input inputMode="numeric" maxLength={6} value={form.otp} onChange={event=>setForm({...form,otp:event.target.value.replace(/\D/g,"")})}/></label>:null}<button className="button button-primary" disabled={busy}>{busy?"Veuillez patienter…":mode==="login"?"Se connecter":"Créer mon compte"}</button><button type="button" className="account-switch" onClick={()=>{setMode(mode==="login"?"register":"login");setMessage("")}}>{mode==="login"?"Pas encore de compte ? S’inscrire":"Déjà inscrit ? Se connecter"}</button>{message?<p role="alert">{message}</p>:null}</form></main></AppShell>;
  const orders=overview?.orders??[];const quotes=overview?.quotes??[];
  return <AppShell><main className="customer-portal"><header><div><span>ESPACE CLIENT</span><h1>Bonjour, {user.email.split("@")[0]}</h1><p>Voici l’état actuel de vos demandes et commandes.</p></div><div>{["DEALER_ADMIN","SUPER_ADMIN"].includes(user.role)?<Link className="button button-primary" href="/dashboard">Administration</Link>:null}<button className="button button-secondary" onClick={()=>void logout()} disabled={busy}>Déconnexion</button></div></header><section className="customer-summary"><article><span>Commandes</span><strong>{orders.length}</strong></article><article><span>Devis</span><strong>{quotes.length}</strong></article><article><span>En livraison</span><strong>{orders.filter(order=>["processing","shipped"].includes(order.status)).length}</strong></article></section>
  <section className="customer-section"><div className="customer-title"><div><span>SUIVI EN TEMPS RÉEL</span><h2>Mes commandes</h2></div><Link href="/catalog">Découvrir le catalogue →</Link></div>{orders.length?<div className="customer-orders">{orders.map(order=>{const current=Math.max(0,orderSteps.indexOf(order.status));return <article key={order.id}><header><div><small>COMMANDE</small><b>#{order.id.slice(0,8).toUpperCase()}</b><span>{new Date(order.created_at).toLocaleDateString("fr-FR")}</span></div><strong>{money(order.total_cents,order.currency)}</strong></header><div className="order-progress">{orderSteps.map((step,index)=><div className={index<=current?"done":""} key={step}><i>{index<current?"✓":index+1}</i><span>{{pending:"Reçue",confirmed:"Confirmée",processing:"Préparation",shipped:"Expédiée",delivered:"Livrée"}[step]}</span></div>)}</div><ul>{order.items.map((item,index)=><li key={index}><span>{item.quantity} × {item.name}</span><b>{money(item.unit_price_cents,order.currency)}</b></li>)}</ul>{order.delivery?<div className="delivery-card"><b>Livraison : {order.delivery.status}</b><span>{order.delivery.carrier??"Transporteur en cours d’attribution"}</span>{order.delivery.tracking_number?<code>{order.delivery.tracking_number}</code>:null}</div>:null}{order.payments.length?<p className="payment-state">Paiement : {order.payments.map(payment=>`${payment.provider} - ${payment.status}`).join(", ")}</p>:null}</article>})}</div>:<div className="customer-empty"><b>Aucune commande pour le moment</b><p>Vos commandes confirmées apparaîtront ici avec leur progression.</p><Link className="button button-primary" href="/catalog">Voir les machines</Link></div>}</section>
  <section className="customer-section"><div className="customer-title"><div><span>DOCUMENTS</span><h2>Mes devis</h2></div><Link href="/quote-request">Nouveau devis →</Link></div>{quotes.length?<div className="quote-documents">{quotes.map(quote=><article key={quote.reference}><div><span>PDF</span><div><b>{quote.reference}</b><small>{quote.product_slug} · {new Date(quote.created_at).toLocaleDateString("fr-FR")}</small></div></div><strong>{money(quote.total_cents,quote.currency)}</strong><em>{quote.status}</em><a className="button button-secondary" href={`${api}/api/customer/quotes/${encodeURIComponent(quote.reference)}/pdf`} target="_blank" rel="noreferrer">Télécharger PDF</a></article>)}</div>:<div className="customer-empty"><b>Aucun devis associé à cette adresse</b><p>Créez votre première demande et elle apparaîtra automatiquement ici.</p><Link className="button button-primary" href="/quote-request">Demander un devis</Link></div>}</section></main></AppShell>;
}
