"use client";

import { useCallback, useState, type FormEvent } from "react";
import Link from "next/link";

const API=(process.env.NEXT_PUBLIC_API_URL??"https://agrifrance-api.onrender.com").replace(/\/$/,"");
type Summary={products:number;active_carts:number;orders:number;paid_deposits:number;paid_amount_cents:string;pending_quotes:number};
type AdminProduct={id:string;name:string;slug:string;brand:string;price_cents:string|null;engine_power_hp:number;transmission_type:string;condition:"new"|"used";stock_status:string;is_active:boolean};
type Cart={id:string;status:string;updated_at:string;email:string|null;items:Array<{name:string;quantity:number;price_cents:string|null}>};
type Order={id:string;status:string;currency:string;total_cents:string|null;created_at:string;email:string|null;items:Array<{name:string;quantity:number}>};
type Payment={id:string;order_id:string;provider:string;provider_reference:string|null;status:string;amount_cents:string;currency:string;created_at:string;email:string|null};
type ProductForm={name:string;slug:string;brand:string;priceCents:string;enginePowerHp:string;transmissionType:string;condition:"new"|"used";stockStatus:string};
const emptyProduct:ProductForm={name:"",slug:"",brand:"AgriFrance",priceCents:"",enginePowerHp:"0",transmissionType:"",condition:"new",stockStatus:"available"};
const money=(cents:string|number|null)=>new Intl.NumberFormat("fr-FR",{style:"currency",currency:"EUR"}).format(Number(cents??0)/100);

export function AdminDashboard(){
  const [csrf,setCsrf]=useState(""); const [user,setUser]=useState<{email:string;role:string}|null>(null); const [login,setLogin]=useState({email:"",password:"",otp:""});
  const [summary,setSummary]=useState<Summary|null>(null); const [products,setProducts]=useState<AdminProduct[]>([]); const [carts,setCarts]=useState<Cart[]>([]); const [orders,setOrders]=useState<Order[]>([]); const [payments,setPayments]=useState<Payment[]>([]);
  const [tab,setTab]=useState<"products"|"carts"|"orders"|"payments">("products"); const [form,setForm]=useState(emptyProduct); const [editing,setEditing]=useState<string|null>(null); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false);
  const request=useCallback(async<T,>(path:string,init:RequestInit={})=>{const response=await fetch(`${API}${path}`,{...init,credentials:"include",headers:{"content-type":"application/json",...(csrf?{"x-csrf-token":csrf}:{}),...init.headers}});const payload=response.status===204?null:await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload?.error??`Erreur ${response.status}`);return payload as T;},[csrf]);
  const load=useCallback(async()=>{setBusy(true);try{const [s,p,c,o,d]=await Promise.all([request<Summary>("/api/admin/summary"),request<{items:AdminProduct[]}>("/api/admin/products"),request<{items:Cart[]}>("/api/admin/carts"),request<{items:Order[]}>("/api/admin/orders"),request<{items:Payment[]}>("/api/admin/payments")]);setSummary(s);setProducts(p.items);setCarts(c.items);setOrders(o.items);setPayments(d.items);setMessage("");}catch(error){setMessage(error instanceof Error?error.message:"Chargement impossible");}finally{setBusy(false);}},[request]);
  const submitLogin=async(event:FormEvent)=>{event.preventDefault();setBusy(true);try{const response=await fetch(`${API}/api/auth/login`,{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify(login)});const payload=await response.json();if(!response.ok)throw new Error(payload.error??"Connexion impossible");if(!["DEALER_ADMIN","SUPER_ADMIN"].includes(payload.user.role))throw new Error("Ce compte ne possède pas les droits administrateur.");setUser(payload.user);setCsrf(payload.csrfToken);setMessage("");await load();}catch(error){setMessage(error instanceof Error?error.message:"Connexion impossible");}finally{setBusy(false);}};
  const saveProduct=async(event:FormEvent)=>{event.preventDefault();setBusy(true);try{const body={...form,priceCents:form.priceCents===""?null:Number(form.priceCents),enginePowerHp:Number(form.enginePowerHp)};await request(editing?`/api/admin/products/${editing}`:"/api/admin/products",{method:editing?"PUT":"POST",body:JSON.stringify(body)});setForm(emptyProduct);setEditing(null);setMessage(editing?"Produit modifié.":"Produit ajouté.");await load();}catch(error){setMessage(error instanceof Error?error.message:"Enregistrement impossible");}finally{setBusy(false);}};
  const edit=(product:AdminProduct)=>{setEditing(product.id);setForm({name:product.name,slug:product.slug,brand:product.brand,priceCents:product.price_cents??"",enginePowerHp:String(product.engine_power_hp),transmissionType:product.transmission_type,condition:product.condition,stockStatus:product.stock_status});window.scrollTo({top:0,behavior:"smooth"});};
  const remove=async(product:AdminProduct)=>{if(!confirm(`Supprimer ${product.name} du catalogue ?`))return;try{await request(`/api/admin/products/${product.id}`,{method:"DELETE"});setMessage("Produit supprimé du catalogue.");await load();}catch(error){setMessage(error instanceof Error?error.message:"Suppression impossible");}};
  const updateOrder=async(id:string,status:string)=>{try{await request(`/api/admin/orders/${id}`,{method:"PATCH",body:JSON.stringify({status})});await load();}catch(error){setMessage(error instanceof Error?error.message:"Mise à jour impossible");}};
  if(!summary)return <main className="admin-login"><Link href="/" className="admin-brand">AGRIFRANCE</Link><form onSubmit={submitLogin}><span>ESPACE SÉCURISÉ</span><h1>Administration</h1><p>Connectez-vous avec un compte Dealer Admin ou Super Admin.</p><label>E-mail<input type="email" required value={login.email} onChange={e=>setLogin({...login,email:e.target.value})}/></label><label>Mot de passe<input type="password" required minLength={12} value={login.password} onChange={e=>setLogin({...login,password:e.target.value})}/></label><label>Code MFA <small>(si configuré)</small><input inputMode="numeric" maxLength={6} value={login.otp} onChange={e=>setLogin({...login,otp:e.target.value.replace(/\D/g,"")})}/></label><button className="button button-primary" disabled={busy}>{busy?"Connexion…":"Se connecter"}</button>{message?<p className="admin-error" role="alert">{message}</p>:null}</form></main>;
  return <main className="admin-shell"><aside className="admin-sidebar"><Link href="/" className="admin-brand">AGRIFRANCE</Link><small>GESTION COMMERCIALE</small>{(["products","carts","orders","payments"] as const).map(value=><button key={value} className={tab===value?"active":""} onClick={()=>setTab(value)}>{value==="products"?"Produits":value==="carts"?"Paniers":value==="orders"?"Commandes":"Dépôts & paiements"}</button>)}<div><span>{user?.email??"Administrateur"}</span><Link href="/">Retour au site</Link></div></aside><section className="admin-main"><header><div><span>TABLEAU DE BORD</span><h1>Vue d’ensemble</h1></div><button className="button button-secondary" onClick={()=>void load()} disabled={busy}>{busy?"Actualisation…":"Actualiser"}</button></header><div className="admin-kpis"><Kpi label="Produits actifs" value={summary.products}/><Kpi label="Paniers actifs" value={summary.active_carts}/><Kpi label="Commandes" value={summary.orders}/><Kpi label="Dépôts confirmés" value={summary.paid_deposits}/><Kpi label="Montant encaissé" value={money(summary.paid_amount_cents)}/><Kpi label="Devis en attente" value={summary.pending_quotes}/></div>{message?<p className="admin-message" role="status">{message}</p>:null}
  {tab==="products"?<><form className="admin-product-form" onSubmit={saveProduct}><h2>{editing?"Modifier le produit":"Ajouter un produit"}</h2><label>Nom<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value,slug:editing?form.slug:e.target.value.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"")})}/></label><label>Slug<input required pattern="[a-z0-9-]+" value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})}/></label><label>Marque<input required value={form.brand} onChange={e=>setForm({...form,brand:e.target.value})}/></label><label>Prix en centimes<input type="number" min="0" value={form.priceCents} onChange={e=>setForm({...form,priceCents:e.target.value})}/></label><label>Puissance (ch)<input type="number" min="0" required value={form.enginePowerHp} onChange={e=>setForm({...form,enginePowerHp:e.target.value})}/></label><label>Transmission<input required value={form.transmissionType} onChange={e=>setForm({...form,transmissionType:e.target.value})}/></label><label>État<select value={form.condition} onChange={e=>setForm({...form,condition:e.target.value as "new"|"used"})}><option value="new">Neuf</option><option value="used">Occasion</option></select></label><label>Stock<select value={form.stockStatus} onChange={e=>setForm({...form,stockStatus:e.target.value})}><option value="available">Disponible</option><option value="low_stock">Stock faible</option><option value="on_order">Sur commande</option></select></label><div><button className="button button-primary" disabled={busy}>{editing?"Enregistrer":"Ajouter"}</button>{editing?<button type="button" className="button button-secondary" onClick={()=>{setEditing(null);setForm(emptyProduct)}}>Annuler</button>:null}</div></form><div className="admin-table-wrap"><table><thead><tr><th>Produit</th><th>Marque</th><th>Prix</th><th>État</th><th>Stock</th><th>Actions</th></tr></thead><tbody>{products.map(product=><tr key={product.id} className={!product.is_active?"muted":""}><td><b>{product.name}</b><small>{product.slug}</small></td><td>{product.brand}</td><td>{money(product.price_cents)}</td><td>{product.condition==="new"?"Neuf":"Occasion"}</td><td>{product.stock_status}</td><td><button onClick={()=>edit(product)}>Modifier</button><button className="danger" onClick={()=>void remove(product)}>Supprimer</button></td></tr>)}</tbody></table></div></>:null}
  {tab==="carts"?<DataList empty="Aucun panier enregistré.">{carts.map(cart=><article key={cart.id}><div><b>Panier {cart.id.slice(0,8)}</b><span>{cart.email??"Visiteur"} · {new Date(cart.updated_at).toLocaleString("fr-FR")}</span></div><strong>{cart.items.reduce((sum,item)=>sum+item.quantity,0)} article(s)</strong><ul>{cart.items.map((item,index)=><li key={index}>{item.quantity} × {item.name} — {money(item.price_cents)}</li>)}</ul></article>)}</DataList>:null}
  {tab==="orders"?<DataList empty="Aucune commande enregistrée.">{orders.map(order=><article key={order.id}><div><b>Commande {order.id.slice(0,8)}</b><span>{order.email??"Client invité"} · {new Date(order.created_at).toLocaleString("fr-FR")}</span></div><strong>{money(order.total_cents)}</strong><select value={order.status} onChange={e=>void updateOrder(order.id,e.target.value)}><option value="pending">En attente</option><option value="confirmed">Confirmée</option><option value="processing">Préparation</option><option value="shipped">Expédiée</option><option value="delivered">Livrée</option><option value="cancelled">Annulée</option></select></article>)}</DataList>:null}
  {tab==="payments"?<DataList empty="Aucun dépôt ou paiement enregistré.">{payments.map(payment=><article key={payment.id}><div><b>{payment.provider} · {payment.provider_reference??payment.id.slice(0,8)}</b><span>{payment.email??"Client"} · {new Date(payment.created_at).toLocaleString("fr-FR")}</span></div><strong>{money(payment.amount_cents)}</strong><em>{payment.status}</em></article>)}</DataList>:null}</section></main>;
}
function Kpi({label,value}:{label:string;value:string|number}){return <article><span>{label}</span><strong>{value}</strong></article>}
function DataList({children,empty}:{children:React.ReactNode;empty:string}){return <div className="admin-data-list">{Array.isArray(children)&&children.length?children:<p>{empty}</p>}</div>}
