"use client";

import Link from "next/link";
import { useTranslation } from "react-i18next";
import { AppShell } from "@/src/components/AppShell";
import { ImageGallery } from "@/src/components/ImageGallery";
import { ProductGrid } from "@/src/components/ProductGrid";
import { useCart } from "@/src/context/CartContext";
import { INDICATIVE_PRICE_NOTICE, products } from "@/src/data/products";
import type { Product } from "@/src/types/product";
import { formatPrice, whatsappUrl } from "@/src/utils/format";

export function ProductPage({ product }: { product: Product }) {
  const { t, i18n } = useTranslation();
  const { addItem } = useCart();
  const similar = products.filter((item) => item.categorySlug === product.categorySlug && item.id !== product.id).slice(0,4);
  const schema = { "@context":"https://schema.org", "@type":"Product", name:product.nom, image:product.images.map((image) => `https://agrifrance.vercel.app${image.src}`), description:product.descriptionCourte, sku:product.id, brand:{"@type":"Brand",name:product.marque}, offers:{"@type":"Offer",priceCurrency:"EUR",price:product.prix,availability:product.disponible?"https://schema.org/InStock":"https://schema.org/PreOrder",url:`https://agrifrance.vercel.app/produits/${product.categorySlug}/${product.slug}`} };
  const whatsAppMessage = `Bonjour AgriFrance, je souhaite vérifier la disponibilité de ${product.nom} (${formatPrice(product.prix, "fr")}).`;
  return <AppShell><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}/><div className="product-breadcrumb"><Link href="/">Accueil</Link><span>/</span><Link href="/catalog">Catalogue</Link><span>/</span><span>{product.nom}</span></div><section className="product-detail"><ImageGallery images={product.images}/><div className="product-purchase"><span className={`availability ${product.disponible ? "in-stock" : ""}`}>{product.disponible ? t("common.available") : t("common.unavailable")} · stock {product.stock}</span><small>{product.categorie} · {product.marque}</small><h1>{product.nom}</h1><p>{t("catalog.description")}</p><div className="detail-price">{product.ancienPrix ? <del>{formatPrice(product.ancienPrix,i18n.resolvedLanguage)}</del> : null}<strong>{formatPrice(product.prix,i18n.resolvedLanguage)}</strong><span>{t("common.indicative")}</span></div><p className="price-notice">{INDICATIVE_PRICE_NOTICE}</p><div className="purchase-actions"><button className="button button-primary" onClick={() => addItem(product.id)} disabled={!product.disponible}>{t("common.addCart")}</button><Link className="button button-secondary" href={`/quote-request?product=${product.id}`}>{t("common.quote")}</Link><a className="button button-whatsapp" href={whatsappUrl(whatsAppMessage)} target="_blank" rel="noreferrer">{t("common.whatsapp")}</a><a className="button button-link" href="tel:+2290197000000">{t("common.call")}</a></div><div className="purchase-trust"><span>✓ {t("home.warranty")}</span><span>✓ {t("home.delivery")}</span><span>✓ {t("product.payment")}</span></div></div></section><section className="product-information"><article><h2>{t("product.description")}</h2><p>{product.descriptionComplete}</p><p>{t("product.placeholder")}</p></article><article><h2>{t("product.specs")}</h2><dl>{[[t("catalog.brand"),product.marque],[t("catalog.model"),product.modele],[t("catalog.power"),product.puissance],[t("catalog.year"),String(product.annee)],[t("catalog.condition"),product.etat],["Transmission",product.transmission],["Utilisation",product.heuresUtilisation],...product.caracteristiques.map((item,index) => [`Option ${index+1}`,item])].map(([label,value]) => <div key={`${label}-${value}`}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></article></section><section className="service-cards"><article><h3>{t("product.delivery")}</h3><p>{t("product.deliveryText")}</p></article><article><h3>{t("product.warranty")}</h3><p>{t("product.warrantyText")}</p></article><article><h3>{t("product.payment")}</h3><p>{t("product.paymentText")}</p></article></section><section className="commerce-section similar-products"><div className="section-heading"><h2>{t("product.similar")}</h2></div><ProductGrid products={similar}/></section><div className="mobile-sticky-action"><strong>{formatPrice(product.prix,i18n.resolvedLanguage)}</strong><button onClick={() => addItem(product.id)} disabled={!product.disponible}>{t("common.addCart")}</button></div></AppShell>;
}
